---
# Markdownlint configuration
# Markdownlint rules reference: https://github.com/markdownlint/markdownlint

default: true

# Allow longer lines (120 chars)
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# Allow inline HTML
MD033: false

# Allow bare URLs
MD034: false
